#PBS -N polyfreqs-octo-f0.01-c20-i30
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=8
#PBS -m ae
#PBS -j oe
set -x

cp $HOME/code/run_polyfreqs.sh $HOME/code/run_polyfreqs.R $TMPDIR/
cd $TMPDIR/ 

module load R

bash run_polyfreqs.sh -i 30 -c 20 -f 0.01 -m octo-f0.01-c20-i30-mcmc.out -p 8

mv octo-f0.01-c20-i30-mcmc.out $HOME/code/sim_data/
mv tot-* $HOME/code/raw_data/
mv ref-* $HOME/code/raw_data/
