#PBS -N polyfreqs-tetra-f0.05-c5-i10
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=8
#PBS -m ae
#PBS -j oe
set -x

cp $HOME/code/run_polyfreqs.sh $HOME/code/run_polyfreqs.R $TMPDIR/
cd $TMPDIR/ 

module load R

bash run_polyfreqs.sh -i 10 -c 5 -f 0.05 -m tetra-f0.05-c5-i10-mcmc.out -p 4

mv tetra-f0.05-c5-i10-mcmc.out $HOME/code/sim_data/
mv tot-* $HOME/code/raw_data/
mv ref-* $HOME/code/raw_data/
